version: "3"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/sonarr/config:/config
      - ${VOL_MEDIA}/hd/tv:/hd
      - ${VOL_MEDIA}/uhd/tv:/uhd
      - ${VOL_DOWNLOADS}:/downloads
    ports:
      - ${SONARR_PORT_8989}:8989
    restart: ${RESTART_POLICY}
