version: "3"
services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/wireshark/config:/config
    # ports:
    #   - ${WIRESHARK_PORT_3000}:3000 #optional
    restart: ${RESTART_POLICY}
