version: "3"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CODE_SERVER_PASSWORD} #optional
      - HASHED_PASSWORD=${CODE_SERVER_HASHED_PASSWORD}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${CODE_SERVER_SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${CODE_SERVER_PROXY_DOMAIN}
      - DOCKER_MODS=${CODE_SERVER_DOCKER_MODS}
    volumes:
      - ${VOL_DOCKER_SOCK}:/var/run/docker.sock
      - ${VOL_CONFIG}/code-server:/config
      - ${VOL_PLAYGROUND}:/playground
    ports:
      - ${CODE_SERVER_PORT_8443}:8443
    restart: ${RESTART_POLICY}
    labels:
      - swag=enable
      - swag_address=code-server
      - swag_port=8443
      - swag_proto=https
      - swag_url=code.***REMOVED***
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/mysql-workbench:/config
    ports:
      - ${MYSQL_WB_PORT_3000}:3000
    cap_add:
      - IPC_LOCK
    restart: ${RESTART_POLICY}
    labels:
      - swag=enable
      - swag_address=mysql-workbench
      - swag_port=3000
      - swag_proto=http
      - swag_url=mysql-workbench.***REMOVED***
