version: "3"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HASHED_PASSWORD=${CODE_SERVER_HASHED_PASSWORD}
      - SUDO_PASSWORD_HASH=${CODE_SERVER_SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${CODE_SERVER_PROXY_DOMAIN}
    volumes:
      - ${VOL_CONFIG}/code-server/config:/config
      - ${VOL_PLAYGROUND}:/playground
    ports:
      - ${CODE_SERVER_PORT_8443}:8443
    restart: ${RESTART_POLICY}
