version: "3.7"
services:

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${VOL_CONFIG}/plex:/config
      - media:/media
      - /trancode:/transcode
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: ${RESTART_POLICY}
    networks:
      - intranet
    labels:
      - swag=enable
      - swag_port=32400
    deploy:
      placement:
        constraints: [ node.hostname == docker-manager-1 ]
        # resources:
        #   reservations:
        #     generic_resources:
        #       - discrete_resource_spec:
        #           kind: 'NVIDIA-GPU'
        #           value: 2
        # devices:
        #   - driver: nvidia
        #     device_ids: [ '0' ]
        #     capabilities: [ gpu ]

volumes:
  media:
    driver_opts:
      type: cifs
      o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},addr=${CIFS_ADDRESS},file_mode=0777,dir_mode=0777,uid=${PUID},gid=${PGID},mfsymlinks,hard,nobrl"
      device: "//${CIFS_ADDRESS}/media"

networks:
  intranet:
    external: true
