version: "3"
services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /data/gv0/config/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
