version: "3"
services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/overseerr/config:/config
    ports:
      - ${OVERSEERR_PORT_5055}:5055
    restart: ${RESTART_POLICY}
