version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DOCKER_MODS=${SWAG_DOCKER_MODS}
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      - EMAIL=${SWAG_EMAIL}
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
      # - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ${VOL_CONFIG}/swag/config:/config
    ports:
      - ${SWAG_PORT_443}:443
      - ${SWAG_PORT_80}:80 #optional
    restart: ${RESTART_POLICY}

  # authelia:
  #   image: authelia/authelia:4.21.0
  #   container_name: authelia
  #   environment:
  #     - TZ=Australia/Melbourne
  #   volumes:
  #     - ${VOL_CONFIG}/authelia/config:/config
  #   restart: ${RESTART_POLICY}
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/homeassistant/config:/config
    # ports:
    # - ${HOMEASSISTANT_PORT_8123}:8123
    # devices:
    #   - /path/to/device:/path/to/device
    restart: ${RESTART_POLICY}
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    hostname: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/ddclient/config:/config
    restart: ${RESTART_POLICY}

