version: "2.1"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Australia/Melbourne
      - BASE_URL=/ #optional
    volumes:
      - /data/gv0/config/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
