version: "3"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=${OMBI_BASE_URL} #optional
    volumes:
      - ${VOL_CONFIG}/ombi/config:/config
    ports:
      - ${OMBI_PORT_3579}:3579
    restart: ${RESTART_POLICY}
