x-environment:
  &environment
  PUID: $PUID
  PGID: $PGID
  TZ: $TZ

x-flame-labels:
  &flame_labels
  flame.type: app
  flame.icon: custom

version: "3.7"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/homeassistant:/config
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Home Assistant
      flame.url: https://home.$DOMAIN
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/grocy:/config
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Grocy
      flame.url: https://grocy.$DOMAIN

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: $RESTART_POLICY
    volumes:
      - $VOL_CONFIG/mqtt:/mosquitto

networks:
  default:
    external: true
    name: intranet
