version: "3.7"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    # env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/homeassistant:/config
    restart: ${RESTART_POLICY}
    labels:
      - swag=enable
      - swag_port=8123
      - swag_proto=http
      - swag_url=home.*
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    # env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/grocy:/config
    restart: ${RESTART_POLICY}
    ports:
      - ${GROCY_PORT_80}:80
    labels:
      - swag=enable

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: ${RESTART_POLICY}
    volumes:
      - ${VOL_CONFIG}/mqtt:/mosquitto
    # ports:
    #   - 1883:1883
    #   - 9001:9001

networks:
  default:
    external: true
    name: intranet
