x-environment:
  &environment
  PUID: $PUID
  PGID: $PGID
  TZ: $TZ
x-networks:
  &networks
  networks:
    - db
    - intranet

x-flame-labels:
  &flame_labels
  flame.type: app
  flame.icon: custom

version: "3.7"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      <<: *environment
      PASSWORD: $CODE_SERVER_PASSWORD
      HASHED_PASSWORD: $CODE_SERVER_HASHED_PASSWORD
      SUDO_PASSWORD: $CODE_SERVER_SUDO_PASSWORD
      SUDO_PASSWORD_HASH: $CODE_SERVER_SUDO_PASSWORD_HASH
      PROXY_DOMAIN: $CODE_SERVER_PROXY_DOMAIN
      DOCKER_MODS: $CODE_SERVER_DOCKER_MODS
      DOCKER_HOST: dockerproxy
    volumes:
      - $VOL_CONFIG/code-server:/config
      - $VOL_PLAYGROUND:/playground
    <<: *networks
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Code
      flame.url: https://code.$DOMAIN

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/mysql-workbench:/config
    <<: *networks
    cap_add:
      - IPC_LOCK
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Workbench
      flame.url: https://workbench.$DOMAIN
  adminer:
    image: adminer
    <<: *networks
    labels:
      <<: *flame_labels
      flame.name: Sql
      flame.url: https://sql.$DOMAIN
networks:
  intranet:
    external: true
  db:
    external: true
