version: "3"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    user: ${USER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/heimdall/config:/config
    restart: ${RESTART_POLICY}
