version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1003
      - PGID=1003
      - VERSION=docker
      - PLEX_CLAIM=claim-yimumPyB5tYYroN1Y4e_
    volumes:
      - /data/gv0/config/plex/config:/config
      - /data/gv0/media:/data/media
    restart: unless-stopped
