version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=2000
      - PGID=2000
      - VERSION=docker
      - PLEX_CLAIM=claim-n3RsL21ZA4BURes3AKuP
    volumes:
      - ./config:/config
      - /data/media:/data/media
    restart: unless-stopped