version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1005
      - PGID=1005
      - VERSION=docker
      - PLEX_CLAIM=claim-n3RsL21ZA4BURes3AKuP
    volumes:
      - /data/gv0/config/plex/config:/config
      - /data/gv0/media:/data/media
    restart: unless-stopped
