version: "3"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /data/gv0/config/homeassistant/config:/config
    # devices:
    #   - /path/to/device:/path/to/device
    restart: unless-stopped
