version: "3"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/homeassistant/config:/config
    ports:
      - ${HOMEASSISTANT_PORT_8123}:8123
      # devices:
    #   - /path/to/device:/path/to/device
    restart: ${RESTART_POLICY}
