x-environment:
  &environment
  PUID: $PUID
  PGID: $PGID
  TZ: $TZ
x-media: &vol_media media:/media
x-downloads: &vol_downloads downloads:/downloads

x-flame-labels:
  &flame_labels
  flame.type: app
  flame.icon: custom

version: "3.7"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/deluge:/config
      - *vol_downloads
    ports:
      - $DELUGE_PORT_6881:6881
      - $DELUGE_PORT_6881:6881/udp
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Deluge
      flame.url: https://deluge.$DOMAIN
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/radarr:/config
      - *vol_media
      - *vol_downloads
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Radarr
      flame.url: https://radarr.$DOMAIN

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/sonarr:/config
      - *vol_media
      - *vol_downloads
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Sonarr
      flame.url: https://sonarr.$DOMAIN

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/lidarr:/config
      - *vol_media
      - *vol_downloads
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Lidarr
      flame.url: https://music.$DOMAIN

  readarr-ebooks:
    image: ghcr.io/linuxserver/readarr:develop
    container_name: readarr-ebooks
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/readarr-ebooks:/config
      - *vol_downloads
      - *vol_media
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Ebooks
      flame.url: https://ebooks.$DOMAIN

  readarr-audiobooks:
    image: ghcr.io/linuxserver/readarr:develop
    container_name: readarr-audiobooks
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/readarr-audiobooks:/config
      - *vol_downloads
      - *vol_media
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Audiobooks
      flame.url: https://audiobooks.$DOMAIN

  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/overseerr:/config
      - *vol_media
      - *vol_downloads
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Overseerr
      flame.url: https://overseerr.$DOMAIN

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/prowlarr:/config
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Prowlarr
      flame.url: https://prowlarr.$DOMAIN

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      <<: *environment
    volumes:
      - $VOL_CONFIG/tautulli:/config
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Tautulli
      flame.url: https://tautulli.$DOMAIN
  # TODO
  # bazarr:
  #   image: ghcr.io/linuxserver/bazarr
  #   container_name: bazarr
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #   volumes:
  #     - $VOL_CONFIG/bazarr:/config
  #     - *vol_media
  #   # ports:
  #   #   - $BAZARR_PORT_6767:6767
  #   restart: $RESTART_POLICY
  #   networks:
  #     - intranet

  # nzbget:
  #   image: lscr.io/linuxserver/nzbget
  #   container_name: nzbget
  #   environment:
  #     - PUID=$PUID}
  #     - PGID=$PGID}
  #     - TZ=$TZ}
  #     - NZBGET_USER=$NZBGET_USER 
  #     - NZBGET_PASS=$NZBGET_PASS 
  #   volumes:
  #     - $VOL_CONFIG/nzbget/config:/config
  #     - $VOL_*vol_downloads
  #   ports:
  #     - $NZBGET_PORT_6789:6789
  #   restart:  $RESTART_POLICY

volumes:
  media:
    driver_opts:
      type: cifs
      o: "username=$CIFS_USERNAME,password=$CIFS_PASSWORD,addr=$CIFS_ADDRESS,file_mode=0755,dir_mode=0755,uid=$PUID,gid=$PGID,mfsymlinks,hard,nobrl"
      device: "//$CIFS_ADDRESS/media"
  downloads:
    driver_opts:
      type: cifs
      o: "username=$CIFS_USERNAME,password=$CIFS_PASSWORD,addr=$CIFS_ADDRESS,file_mode=0755,dir_mode=0755,uid=$PUID,gid=$PGID,mfsymlinks,hard,nobrl"
      device: "//$CIFS_ADDRESS/downloads"

networks:
  default:
    external: true
    name: intranet
