version: "3"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    user: ${USER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/nextcloud/config:/config
      - ${VOL_DOCUMENTS}/nextcloud:/data
    ports:
      - ${NEXTCLOUD_PORT_443}:443
    restart: ${RESTART_POLICY}
