version: "3"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Australia/Melbourne
    volumes:
      - /data/config/nextcloud/config:/config
      - /data/gv0/media:/data/media
      - /data/gv0/documents:/data/documents
      - /data/gv0/nextcloud/nextcloud:/data/db
    # ports:
    #   - 8443:443
    restart: unless-stopped
