version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Australia/Melbourne
    volumes:
      - /data/gv0/config/nextcloud/config:/config
      - /data/gv0/media:/data/media
      - /data/gv0/documents:/data/documents
    ports:
      - 443:443
    restart: unless-stopped
