version: "3"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/radarr/config:/config
      - ${VOL_MEDIA}/hd/movies:/hd
      - ${VOL_MEDIA}/uhd/movies:/uhd
      - ${VOL_DOWNLOADS}:/downloads
    ports:
      - ${RADARR_PORT_7878}:7878
    restart: ${RESTART_POLICY}
