version: "3"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Australia/Melbourne
    volumes:
      - /data/gv0/config/calibre-web/config:/config
      - /data/gv0/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
