version: "3"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    user: ${USER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=${JACKETT_AUTO_UPDATE} #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ${VOL_CONFIG}/jackett/config:/config
      - ${VOL_DOWNLOADS}:/downloads
    ports:
      - ${JACKETT_PORT_9117}:9117
    restart: ${RESTART_POLICY}
