version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${VOL_CONFIG}/plex/config:/config
      - ${VOL_MEDIA}:/data/media
    restart: ${RESTART_POLICY}
