version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_MYSQL_DATABASE}
      - MYSQL_USER=${MARIADB_MYSQL_USER}
      - MYSQL_PASSWORD=${MARIADB_MYSQL_PASSWORD}
    volumes:
      - ${VOL_CONFIG}/mariadb/config:/config
      - ${VOL_DATA}/mariadb/databases:/config/databases
    ports:
      - ${MARIADB_PORT_3306}:3306
    restart: ${RESTART_POLICY}
  redis-master:
    image: bitnami/redis:latest
    ports:
      - ${REDIS_MASTER_PORT_6379}:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_MASTER_PASSWORD}
    volumes:
      # - ${VOL_CONFIG}/redis-master/config:/opt/bitnami/redis/mounted-etc
      - ${VOL_DATA}/redis-master/bitnami:/bitnami
    restart: ${RESTART_POLICY}
  redis-replica:
    image: bitnami/redis:latest
    ports:
      - ${REDIS_SLAVE_PORT_6379}:6379
    depends_on:
      - redis-master
    # volumes:
      # - ${VOL_CONFIG}/redis-replica/config:/opt/bitnami/redis/mounted-etc
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_MASTER_PASSWORD}
      - REDIS_PASSWORD=${REDIS_SLAVE_PASSWORD}
    restart: ${RESTART_POLICY}