x-networks:
  &networks
  networks:
    - db
    - intranet

x-flame-labels:
  &flame_labels
  flame.type: app
  flame.icon: custom

x-environment:
  &environment
  PUID: $PUID
  PGID: $PGID
  TZ: $TZ

version: "3.7"
services:
  fireflyiii:
    image: fireflyiii/core:latest
    volumes:
      - $VOL_CONFIG/fireflyiii/upload:/var/www/html/storage/upload
    ports:
      - $FIREFLY_III_PORT_8080:8080
    <<: *networks
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Wallet
      flame.url: https://wallet.$DOMAIN

  fidi:
    image: fireflyiii/data-importer:latest
    # env_file: fidi.env
    restart: $RESTART_POLICY
    ports:
      - $FIDI_PORT_8080:8080
    <<: *networks

    labels:
      <<: *flame_labels
      flame.name: Sync Wallet
      flame.url: https://fidi.$DOMAIN

  vaultwarden:
    user: "$PUID:$PGID"
    image: vaultwarden/server:latest
    environment:
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - $VOL_CONFIG/vaultwarden:/data
    restart: $RESTART_POLICY
    <<: *networks
    labels:
      <<: *flame_labels
      flame.name: Vault Warden
      flame.url: https://pass.$DOMAIN
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      TZ: $TZ
      REDIS_URL: $PAPERMERGE_REDIS_URL
      DB_USER: $PAPERMERGE_DB_USER
      DB_NAME: $PAPERMERGE_DB_NAME
      DB_PASSWORD: $PAPERMERGE_DB_PASSWORD
      DB_HOST: $PAPERMERGE_DB_HOST
      DB_PORT: $PAPERMERGE_DB_PORT
    volumes:
      - $VOL_CONFIG/papermerge/config:/config
      - $VOL_CONFIG/papermerge/data:/data
    restart: $RESTART_POLICY
    <<: *networks
    labels:
      <<: *flame_labels
      flame.name: Papermerge
      flame.url: https://docs.$DOMAIN

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      <<: *environment
      APP_URL: $BOOKSTACK_APP_URL
      DB_HOST: $BOOKSTACK_DB_HOST
      DB_USER: $BOOKSTACK_DB_USER
      DB_PASS: $BOOKSTACK_DB_PASS
      DB_DATABASE: $BOOKSTACK_DB_DATABASE
    volumes:
      - $VOL_CONFIG/bookstack:/config
    restart: unless-stopped
    <<: *networks
    labels:
      <<: *flame_labels
      flame.name: Wiki
      flame.url: https://wiki.$DOMAIN

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      <<: *environment
    networks:
      - intranet
    volumes:
      - $VOL_CONFIG/nextcloud:/config
      - $VOL_DRIVE:/data
    restart: $RESTART_POLICY
    labels:
      <<: *flame_labels
      flame.name: Nextcloud Drive
      flame.url: https://drive.$DOMAIN

networks:
  intranet:
    external: true
  db:
    external: true
