# docker run -d \
# -v firefly_iii_upload:/var/www/html/storage/upload \
# -p 80:8080 \
# -e APP_KEY=CHANGEME_32_CHARS \
# -e DB_HOST=CHANGEME \
# -e DB_PORT=3306 \
# -e DB_CONNECTION=mysql \
# -e DB_DATABASE=CHANGEME \
# -e DB_USERNAME=CHANGEME \
# -e DB_PASSWORD=CHANGEME \
# jc5x/firefly-iii:latest

version: "3"

services:
  fireflyiii:
    image: firefly-iii/core:latest
    volumes:
      - ${VOL_CONFIG}/firefly/upload:/var/www/html/storage/upload
    ports:
      - ${FIREFLY_III_PORT_8080}:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ${VOL_CONFIG}/fireflydb/mysql:/var/lib/mysql
  spectreimporter:
    image: fireflyiii/spectre-importer:latest
    environment:
      - FIREFLY_III_ACCESS_TOKEN=${SPECTRE_IMPORTER_FIREFLY_III_ACCESS_TOKEN}
      - FIREFLY_III_URL=${SPECTRE_IMPORTER_FIREFLY_III_URL}
      - SPECTRE_APP_ID=${SPECTRE_IMPORTER_SPECTRE_APP_ID}
      - SPECTRE_SECRET=${SPECTRE_IMPORTER_SPECTRE_SECRET}
    ports:
      - ${SPECTRE_IMPORTER_PORT_8080}:8080
