version: "3"

services:
  fireflyiii:
    image: fireflyiii/core:latest
    volumes:
      - ${VOL_CONFIG}/firefly/upload:/var/www/html/storage/upload
    ports:
      - ${FIREFLY_III_PORT_8080}:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ${VOL_CONFIG}/fireflydb/mysql:/var/lib/mysql
  spectreimporter:
    image: fireflyiii/spectre-importer:latest
    environment:
      - FIREFLY_III_ACCESS_TOKEN=${SPECTRE_IMPORTER_FIREFLY_III_ACCESS_TOKEN}
      - FIREFLY_III_URL=${SPECTRE_IMPORTER_FIREFLY_III_URL}
      - SPECTRE_APP_ID=${SPECTRE_IMPORTER_SPECTRE_APP_ID}
      - SPECTRE_SECRET=${SPECTRE_IMPORTER_SPECTRE_SECRET}
    ports:
      - ${SPECTRE_IMPORTER_PORT_8080}:8080
