version: "3.6"
services:
  redis-node-0:
    # user: "${PUID}:${PGID}"
    image: docker.io/bitnami/redis-cluster:6.2
    # volumes:
    #   - ${VOL_GLUSTER_VOLUMES}/redis/node-0:/opt/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2
  redis-node-1:
    # user: "${PUID}:${PGID}"
    image: docker.io/bitnami/redis-cluster:6.2
    # volumes:
    # - ${VOL_GLUSTER_VOLUMES}/redis/node-1:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2
  redis-node-2:
    # user: "${PUID}:${PGID}"
    image: docker.io/bitnami/redis-cluster:6.2
    # volumes:
    # - ${VOL_GLUSTER_VOLUMES}/redis/node-2:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWD}
      - REDISCLI_AUTH=${REDIS_PASSWD}
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2
      - REDIS_CLUSTER_CREATOR=yes
networks:
  default:
    external:
      name: db
