version: "3"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INTERFACE=${OPENVPN_AS_INTERFACE} #optional
    volumes: - ${VOL_CONFIG}/openvpn-as/config:/config
    ports:
      - ${OPENVPN_AS_PORT_943}:943
      - ${OPENVPN_AS_PORT_9443}:9443
      - ${OPENVPN_AS_PORT_1194}:1194/udp
    restart: ${RESTART_POLICY}
