version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MARIADB_MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=${MARIADB_MYSQL_DATABASE}
      - MYSQL_USER=${MARIADB_MYSQL_USER}
      - MYSQL_PASSWORD=${MARIADB_MYSQL_PASSWORD}
    volumes:
      - ${VOL_CONFIG}/mariadb/config:/config
    ports:
      - ${MARIADB_PORT_3306}:3306
    restart: ${RESTART_POLICY}
