version: "3"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/bazarr/config:/config
      - ${VOL_MEDIA}/hd:/hd
      - ${VOL_MEDIA}/uhd:/uhd
    ports:
      - ${BAZARR_PORT_6767}:6767
    restart: ${RESTART_POLICY}
