version: "3"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    user: ${USER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/bazarr/config:/config
      - ${VOL_MEDIA}/hd:/data/media/hd
      - ${VOL_MEDIA}/uhd:/data/media/uhd
    ports:
      - ${BAZARR_PORT_6767}:6767
    restart: ${RESTART_POLICY}
