version: "3"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/lidarr/config:/config
      - ${VOL_MEDIA}/music:/music
      - ${VOL_DOWNLOADS}/music:/downloads
    ports:
      - ${Lidarr_PORT_8686}:8686
    restart: ${RESTART_POLICY}
