version: "3"
services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /data/gv0/config/wireshark/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
