version: "3"
services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    user: ${USER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/wikijs/config:/config
      - ${VOL_DOCUMENTS}/wikijs:/data
    ports:
      - ${WIKIJS_PORT_3000}:3000
    restart: ${RESTART_POLICY}
