version: "3"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/syncthing/config:/config
      - ${VOL_DOCUMENTS}:/documents
    ports:
      - ${SYNCTHING_PORT_8384}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    sysctls:
      - net.core.rmem_max=2097152
    restart: ${RESTART_POLICY}
