version: "3.7"
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${VOL_CONFIG}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: ${RESTART_POLICY}
  # TODO
  # endlessh:
  #   image: lscr.io/linuxserver/endlessh
  #   container_name: endlessh
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - MSDELAY=${ESSH_MSDELAY}
  #     - MAXLINES=${ESSH_MAXLINES}
  #     - MAXCLIENTS=${ESSH_MAXCLIENTS}
  #     - LOGFILE=${ESSH_LOGFILE}
  #     - BINDFAMILY=${ESSH_BINDFAMILY}
  #   volumes:
  #     - ${VOL_CONFIG}/endlessh:/config
  #   ports:
  #     - ${ENDLESSH_PORT_2222}:2222
  #   restart: ${RESTART_POLICY}
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false
      - DB_TYPE=${LS_DB_TYPE}
      - DB_NAME=${LS_DB_NAME}
      - DB_HOSTNAME=${LS_DB_HOSTNAME}
      - DB_USERNAME=${LS_DB_USERNAME}
      - DB_PASSWORD=${LS_DB_PASSWORD}
      - DB_PORT=${LS_DB_PORT}
    volumes:
      - ${VOL_CONFIG}/librespeed:/config
    restart: ${RESTART_POLICY}
    networks:
      - db
    labels:
      - flame.type=app
      - flame.name=Speed Test
      - flame.url=https://speedtest.${DOMAIN}
      - flame.icon=custom
networks:
  default:
    external:
      name: intranet
  db:
    external: true
