version: "3.7"
services:
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared
    command: tunnel run ${TUNNEL_NAME}
    volumes:
      - ${VOL_CONFIG}/cloudflared:/etc/cloudflared/
      # secrets:
      # - cf_tunnel_token
    environment:
      - TUNNEL_NAME=${TUNNEL_NAME}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      # - TUNNEL_TOKEN_FILE=/run/secrets/cf_tunnel_token
    restart: ${RESTART_POLICY}
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${VOL_CONFIG}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      # ports:
      #   - 5005:5005
      # secrets:
      #   - flame_password
      # environment:
      #   - PASSWORD=
      # - PASSWORD_FILE=/run/secrets/flame_password
    restart: ${RESTART_POLICY}
  # heimdall:
  #   image: ghcr.io/linuxserver/heimdall
  #   container_name: heimdall
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${VOL_CONFIG}/heimdall:/config
  #   restart: ${RESTART_POLICY}
  #   networks:
  #     - intranet
  # librespeed:
  #   image: lscr.io/linuxserver/librespeed
  #   container_name: librespeed
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - PASSWORD=PASSWORD
  #     - CUSTOM_RESULTS=false
  #     - DB_TYPE=${LS_DB_TYPE}
  #     - DB_NAME=${LS_DB_NAME}
  #     - DB_HOSTNAME=${LS_DB_HOSTNAME}
  #     - DB_USERNAME=${LS_DB_USERNAME}
  #     - DB_PASSWORD=${LS_DB_PASSWORD}
  #     - DB_PORT=${LS_DB_PORT}
  #   volumes:
  #     - ${VOL_CONFIG}/librespeed:/config
  #   restart: ${RESTART_POLICY}
  #   networks:
  #     - db
networks:
  db:
    external: true
  default:
    external:
      name: intranet
secrets:
  flame_password:
    external: true
  cf_tunnel_token:
    external: true
