version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DOCKER_MODS=${SWAG_DOCKER_MODS}
      - EMAIL=${SWAG_EMAIL}
    volumes:
      - ${VOL_CONFIG}/swag/config:/config
    # ports:
    #   - ${SWAG_PORT_443}:443
    #   - ${SWAG_PORT_80}:80 #optional
    restart: ${RESTART_POLICY}
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    hostname: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/ddclient/config:/config
    restart: ${RESTART_POLICY}
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/heimdall/config:/config
    restart: ${RESTART_POLICY}
