version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DOCKER_MODS=${SWAG_DOCKER_MODS}
      - EMAIL=${SWAG_EMAIL}
      - EXTRA_DOMAINS=${SWAG_EXTRA_DOMAINS}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
    volumes:
      - ${VOL_CONFIG}/swag/config:/config
    # ports:
    #   - ${SWAG_PORT_443}:443
    #   - ${SWAG_PORT_80}:80 #optional
    restart: ${RESTART_POLICY}
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    hostname: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/ddclient/config:/config
    restart: ${RESTART_POLICY}
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/heimdall/config:/config
    restart: ${RESTART_POLICY}
  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=${TZ}
    volumes:
      - ${VOL_CONFIG}/authelia/config:/config
    ports:
      - ${AUTHELIA_PORT_9091}:9091
    restart: ${RESTART_POLICY}
  endlessh:
    image: lscr.io/linuxserver/endlessh
    container_name: endlessh
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MSDELAY=${ESSH_MSDELAY}
      - MAXLINES=${ESSH_MAXLINES}
      - MAXCLIENTS=${ESSH_MAXCLIENTS}
      - LOGFILE=${ESSH_LOGFILE}
      - BINDFAMILY=${ESSH_BINDFAMILY}
    volumes:
      - ${VOL_CONFIG}/endlessh/config:/config
    ports:
      - ${ENDLESSH_PORT_2222}:2222
    restart: ${RESTART_POLICY}
  # nextcloud:
  #   image: ghcr.io/linuxserver/nextcloud
  #   container_name: nextcloud
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${VOL_CONFIG}/nextcloud/config:/config
  #     - ${VOL_DOCUMENTS}/nextcloud:/data
  #     - ${NEXTCLOUD_EXTERNAL_MOUNT}:/mnt
  #   ports:
  #     - ${NEXTCLOUD_PORT_443}:443
  #   restart: ${RESTART_POLICY}
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false
      - DB_TYPE=${LS_DB_TYPE}
      - DB_NAME=${LS_DB_NAME}
      - DB_HOSTNAME=${LS_DB_HOSTNAME}
      - DB_USERNAME=${LS_DB_USERNAME}
      - DB_PASSWORD=${LS_DB_PASSWORD}
      - DB_PORT=${LS_DB_PORT}
    volumes:
      - ${VOL_CONFIG}/librespeed/config:/config
    ports:
      - ${LS_DB_PORT}:${LS_DB_PORT}
    restart: ${RESTART_POLICY}